name: continuous-delivery
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: "What to tag the deployer image with"
        required: true
      cnpg_tag:
        description: "What version of the CNPG chart to bundle"
        required: true
jobs:
  build:
    name: Build chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1.1.1
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GCR_JSON_KEY }}'
      - uses: 'docker/login-action@v1'
        with:
          registry:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          id: install

      # Steps to run on tag
      - name: Parse major, minor, patch from tag
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        if: ${{ github.ref_type == 'tag' }}
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '^[v]?([0-9]+\.[0-9]+\.[0-9]).*$'
      - name: Update CNPG chart by tag
        run: make update-chart
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: "${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}"
      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: .
          push: true
          tags: |
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:latest
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ github.ref }}
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
          build-args: |
            TAG=${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
      #####

      # Steps to run on dispatch
      - name: Parse major, minor, patch from tag
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          input_string: ${{ inputs.tag }}
          version_extractor_regex: '^[v]?([0-9]+\.[0-9]+\.[0-9]).*$'
      - name: Update CNPG chart by input
        run: make update-chart
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          TAG: ${{ inputs.cnpg_tag }}
      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          context: .
          push: true
          tags: |
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:latest
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ inputs.tag }}
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            gcr.io/public-edb-ppas/edb-cnp-gke-autopilot-dev/deployer:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
          build-args: |
            TAG=${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
      #####
